### ISSUE TITLE
AttributeError: 'Pix2PixHDModel' object has no attribute 'optimizer_G'

### ISSUE THREAD

**Issue by joel1895** [switchablenorms/DeepFashion_Try_On#51]
I have searched the entire repo but still couldnt find the solution

Traceback (most recent call last):
  File "train.py", line 192, in <module>
    model.module.optimizer_G.zero_grad()
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Pix2PixHDModel' object has no attribute 'optimizer_G'

**Comment by HAN-YANG-HIT** [comment]
Maybe you run the wrong script. Use ACGPN_train/train.py
